DROP DATABASE IF EXISTS hw04;

DROP ROLE IF EXISTS dbo;

CREATE ROLE dbo LOGIN
   ENCRYPTED PASSWORD '123456';
   NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
   
CREATE DATABASE hw04
   WITH OWNER = dbo ENCODING = 'UTF8';